domain_path.settings:
  type: config_object
  mapping:
    entity_types:
      label: Enabled entity types for domain paths
      type: sequence
      sequence:
        type: string

pathauto.pattern.*.third_party.domain_path:
  type: mapping
  label: 'Domains pathauto settings'
  mapping:
    domains:
      type: sequence
      label: 'Domains'
      sequence:
        type: string
        label: 'Domain machinename'